### ISSUE TITLE
作者你好.有事情想要qq联系一下你

### ISSUE THREAD

**Issue by kyokusanaki** [fz6m/swcr#1]
看到了请回复.希望您能修改一下，可以有偿求助

**Comment by kyokusanaki** [comment]
修改插件

**Comment by fz6m** [comment]
> 修改插件

请到对应的项目下面提 issue

**Comment by kyokusanaki** [comment]
https://github.com/fz6m/nonebot-plugin/tree/master/CQGrail该插件下无法提交，希望魔改其中的圣杯战争插件到hoshino上使用或者nb2上使用，但是我不会改




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fz6m/swcr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fz6m/swcr] 作者你好.有事情想要qq联系一下你 (Issue #1)





  
修改插件
  
请到对应的项目下面提 issue
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
